name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        options: --health-cmd="exit 0" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "YourStrong!Passw0rd"  # Replace with a strong password
        # The service will expose SQL Server on port 1433 and wait until SQL Server is healthy

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: Set up SQL Server tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
        # Add sqlcmd to the path
        echo "export PATH=$PATH:/opt/mssql-tools/bin" >> ~/.bashrc
        source ~/.bashrc


    - name: Wait for SQL Server to be ready
      run: |
        # Wait for SQL Server to be available before proceeding
        while ! nc -z localhost 1433; do
        echo "Waiting for SQL Server..."
        sleep 5
        done
        echo "SQL Server is up and running."

    # Add the restore database step

    - name: Create Database if not exists
      run: |
        # Run SQL to create the database (if not exists)
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'FirstWebApiNotes') CREATE DATABASE FirstWebApiNotes;"

    - name: Install dotnet-ef tool
      run: |
        dotnet tool install --global dotnet-ef
        echo "$(dotnet --list-sdks)"

    - name: Copy .bak file into container
      run: |
        # Make sure the DBbackups directory exists
        ls -la /home/runner/work/WebApplication/WebApplication/DBbackups
        cp /home/runner/work/WebApplication/WebApplication/DBbackups/TestFirstWebApiNotes.bak /tmp/TestFirstWebApiNotes.bak

    - name: Restore database from backup
      run: |
        # Ensure the .bak file is accessible from within the container
        ls -la /tmp
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong!Passw0rd" -Q "RESTORE DATABASE FirstWebApiNotes FROM DISK='/tmp/TestFirstWebApiNotes.bak' WITH REPLACE"


    - name: Apply Entity Framework Migrations
      run: |
        dotnet ef database update --project ./FirstWebApi/FirstWebApi.csproj --configuration Release --context DataContextEF
      env:
        # Connection string for your tests. Update accordingly.
        # Set the environment to "Testing" for this run
        ASPNETCORE_ENVIRONMENT: "Testing"

    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        # Connection string for your tests. Update accordingly.
        # Set the environment to "Testing" for this run
        ASPNETCORE_ENVIRONMENT: "Testing"