name: .NET CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Job 1: Setup and Build
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Build project
      - name: Build
        run: dotnet build --no-restore

  # Job 2: Start SQL Server container with docker-compose
  database-setup:
    runs-on: ubuntu-latest
    needs: setup-and-build   # This job runs after the setup-and-build job
    steps:
      # Install Docker (Using official installation script)
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker
          sudo systemctl enable docker

      # Create and start SQL Server container
      - name: Start SQL Server container
        run: |
          echo "version: '3.8'
          services:
            sqlserver:
              image: mcr.microsoft.com/mssql/server:2019-latest
              ports:
                - 1433:1433
              environment:
                ACCEPT_EULA: 'Y'
                SA_PASSWORD: 'YourStrong!Passw0rd'
          " > docker-compose.yml
          docker-compose up -d

      # Wait for SQL Server to be ready
      - name: Wait for SQL Server to be ready
        run: |
          while ! nc -z localhost 1433; do
            echo "Waiting for SQL Server..."
            sleep 5
          done
          echo "SQL Server is up and running."

  
